### ISSUE TITLE
Cann't controll nor preview using `usb_streamer.py`

### ISSUE THREAD

**Issue by mksmaks** [dino-lite/DNX64-Python-API#1]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Following correct initialization steps

- [X] Confirm

### Windows version

11 23H2

### Python version

Python 3.12.0

### Nominatim/Country Codes

DE

### Python env

```
certifi==2023.11.17
charset-normalizer==3.3.2
docopt==0.6.2
idna==3.6
numpy==1.26.2
opencv-python==4.8.0.76
pywin32==306
requests==2.31.0
urllib3==2.1.0
yarg==0.1.9
```

### How to reproduce the issue?

1. Connect DL AM75...
2. run usb_streamer.py

### Expected behavior

A window with the DL camera output is shown. The cameras settings can be controlled by the given commandos. 

### Additional information

When starting the program the first time after a connection via usb is established, the LEDs turn on. 
Starting it a second time, nothing happens.

Running a sample program e.g.:
```
micro_scope = DNX64(dll_path)
device_id = 0

micro_scope.SetVideoDeviceIndex(device_id)

print(micro_scope.GetVideoDeviceIndex())
print(micro_scope.GetVideoDeviceName(device_id))

print(micro_scope.GetDeviceIDA(device_id))

micro_scope.SetLEDState(device_id, 0)
time.sleep(1)
micro_scope.SetLEDState(device_id, 1)
time.sleep(1)
micro_scope.SetLEDState(device_id, 0)
time.sleep(1)
```
    
prints the name and IDA, but does not control the LEDs for example.

**Comment by CharlesChiuGit** [comment]
Hi, @mksmaks !
We're currently off duty, so I can only give you limited assistance, sorry about that. 

Did your computer connected to other usb devices with camera while using DL products?

**Comment by CharlesChiuGit** [comment]
`DNX64` can only function normally when previewing is established, which isn't stated in our current documentation. We felt deeply sorry about that.

Form the sample program you given, it seems like you had not established previewing, could you add opening a preview window and give it another try?

Please that us know if this approach fixes your problem, sorry again for causing you trouble.

**Comment by CharlesChiuGit** [comment]
Hi, @mksmaks 

`SetLEDState()` can only function normally when previewing is established, which is stated in [our current documentation](https://github.com/dino-lite/DNX64-Python-API/blob/d5ef0f9ee2bb824ac451c1c3eb11b49479c6480d/DNX64/__init__.py).

Form the sample program you given, it seems like you had not established preview window, could you add one and give it another try?

Please that us know if this approach fixes your problem.

**Comment by CharlesChiuGit** [comment]
We add two simple preview methods and some documentation at this commit: https://github.com/dino-lite/DNX64-Python-API/commit/f42d97a2d2e2f58f567ff08b9bc006a6f44112e3. PTAL.

**Comment by mksmaks** [comment]
Hi, thanks for coming back at me!
I did not connect any other usb devices. I am developing on a laptop, so I think idx 0 is always my internal webcam. When I set device_index to 1, I get an error with "self.dnx64.SetVideoDeviceIndex(device_index)" in your usb_streamer.py.
`OSError: [WinError -529697949] Windows Error 0xe06d7363`

I will try your example!

**Comment by CharlesChiuGit** [comment]
We separate `CAM_INDEX` form `DEVICE_INDEX` since `DEVICE_INDEX` is for dino-lite products, but `CAM_INDEX` is for opencv objects. If those two variable aren't set properly, you will indeed get a `WinError` according to our tests.

**Comment by mksmaks** [comment]
See also pull request. It might be wrong after reading your answer. 
I can preview when I set
`cap = cv2.VideoCapture(1)`
But not when 
`CAM_INDEX = 1
cap = cv2.VideoCapture(0)` only. 

Or did I misunderstand?

**Comment by CharlesChiuGit** [comment]
I forgot to change the variable name! Thanks for the PR, just merged it!

**Comment by CharlesChiuGit** [comment]
@mksmaks 

Is there anymore errors?

**Comment by mksmaks** [comment]
The usb_streamer works now, when setting CAM_INDEX to 1, thank you very much. 
I can not yet fully control the cam, e.g. setting LED or FLC. If you have any idea on how to fix that, Id be glad as well.

I will check soon if I can work with a second DL as well.

But from here I can start to develop my program, thanks again!

**Comment by CharlesChiuGit** [comment]
> I can not yet fully control the cam, e.g. setting LED or FLC. If you have any idea on how to fix that, Id be glad as well.

Could you show us your program for further investigation? If it's not suitable to post it on github, you could also send an email to charles@anmo.com.tw .

**Comment by CharlesChiuGit** [comment]
@mksmaks 

> I can not yet fully control the cam, e.g. setting LED or FLC. If you have any idea on how to fix that, Id be glad as well.

Could you show us your program for further investigation? If it's not suitable to post it on github, you could also send an email to charles@anmo.com.tw .

Or specify which step you encounter difficulties.

**Comment by CharlesChiuGit** [comment]
close due to inactivity.
