### ISSUE TITLE
cannot run usb_example.py, Dino Camera: AM4113T(R9)

### ISSUE THREAD

**Issue by nootherme** [dino-lite/DNX64-Python-API#9]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Following correct initialization steps

- [X] Confirm

### Windows version

Window10 pro 21H1

### Python version

Python 3.7.8

### Nominatim/Country Codes

US

### Python env

N/A

### How to reproduce the issue?

Errors occurring when running the supplied usb_example.py

Traceback (most recent call last):
  File "C:\Python36\Programs\dino-camera\dnx64_python\usb_example.py", line 16, in <module>
    microscope = DNX64(DNX64_PATH)
  File "C:\Python36\Programs\dino-camera\dnx64_python\dnx64.py", line 49, in __init__
    self.dnx64 = ctypes.CDLL(dll_path)
  File "C:\Python36\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

### Expected behavior

Not sure what to expect

**Comment by CharlesChiuGit** [comment]
It seems like you haven't place the required dll as [prerequisites](https://github.com/dino-lite/DNX64-Python-API#prerequisites).

Make sure you follow the guides.

**Comment by nootherme** [comment]
> It seems like you haven't place the required dll as [prerequisites](https://github.com/dino-lite/DNX64-Python-API#prerequisites).
> 
> Make sure you follow the guides.

Thanks for the advice. I checked the requirements again following your suggestion. 
          The version of the dll is v1.0.11.
          DNX32.dll, DNX64.dll, and libusbK.dll can be found in the same default directory: C:\Program Files\DNX64

This seems to agree with the requirement.  The screenshot of the default folder is attached. 

Any advice is highly appreciated. Thanks.
![DLL_Dino](https://github.com/user-attachments/assets/9b03ace2-fd2f-4222-8d99-0ffa1cb59a6c)

**Comment by nootherme** [comment]
It seems that I can load the dll when moving the required files out of the default directory. 

> It seems like you haven't place the required dll as [prerequisites](https://github.com/dino-lite/DNX64-Python-API#prerequisites).
> 
> Make sure you follow the guides.

**Comment by CharlesChiuGit** [comment]
So `usb_example.py` is working after you move the DLLs out of the default dir?

**Comment by CharlesChiuGit** [comment]
@nootherme 
So `usb_example.py` is working after you move the DLLs out of the default dir?

**Comment by nootherme** [comment]
> @nootherme So `usb_example.py` is working after you move the DLLs out of the default dir?

Yes, Sir! The error disappeared. I don't have access to the camera now and will try it when I get my hand on it. Thanks.
